modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/lehjr/MachineMusePowersuits/issues"
license='Simplified BSD License https://opensource.org/license/bsd-2-clause/'
[[mods]]
    modId="numina"
    version="${mod_version}"
    displayName="Numina"
    updateJSONURL="https://mc-curse-update-checker.herokuapp.com/235440"
    displayURL="https://github.com/lehjr/MachineMusePowersuits"
    authors="MachineMuse, lehjr"
    description="A common library of useful functions and utilities for dealing with Minecraft's source code."

[[dependencies.numina]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    side="BOTH"

[[dependencies.numina]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    side="BOTH"

[[dependencies.numina]]
    modId="jei"
    mandatory=false
    versionRange="${jei_version}"
    ordering="AFTER"
    side="BOTH"
